version: 1.0.{build}
image: Visual Studio 2017

before_build:
  - nuget restore
build_script:
  - choco install "msbuild-sonarqube-runner" -y
#   - MSBuild.SonarQube.Runner.exe begin /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=422b7e86ba596f2972284cf1635032b708dd2c1d"
#   - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=422b7e86ba596f2972284cf1635032b708dd2c1d"
  - SonarScanner.MSBuild.exe begin /k:"learnwithmentor-server1" /d:sonar.organization="dinovoh-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="422b7e86ba596f2972284cf1635032b708dd2c1d"
  - MsBuild.exe /t:Rebuild
  - SonarScanner.MSBuild.exe end /d:sonar.login="422b7e86ba596f2972284cf1635032b708dd2c1d"
  
sonar-scanner -Dsonar.analysis.mode=preview \
              -Dsonar.github.pullRequest=$PULL_REQUEST_ID \
              -Dsonar.github.repository=myOrganisation/myProject \
              -Dsonar.github.oauth="a19a155232cd502b444bf7c4012c18ef32eedd24" \
              -Dsonar.host.url=https://server/sonarqube \
              -Dsonar.login="422b7e86ba596f2972284cf1635032b708dd2c1d"
  

